config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'

  get 'auth/google_oauth2/callback', to: 'sessions#omniauth'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new' # controller and action
  post '/signup', to: 'users#create'
  resources :users, except: [:destroy]
  
  get '/spellbooks/recent_spellbooks' => 'spellbooks#recent_spellbooks' , as: 'recent_spellbooks'

  resources :crystal_balls
  resources :spells
  resources :spellbooks do
    resources :spells
  end

  match '*path' => 'application_controller#fallback', via: [:all] 

  

 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/spellbook.rb
class Spellbook < ApplicationRecord

    has_many :spells
    has_many :users, through: :spells
    
    


    validates :title, :category, presence: true
    validates :level, presence: true, numericality: {greater_than: 0, less_than_or_equal_to: 10}
    

    def self.newest_spellbooks
        Spellbook.order(created_at: :desc).limit(5)
    end

end

app/controllers/spellbooks_controller.rb
class SpellbooksController < ApplicationController
 
    before_action :redirect_if_not_logged_in, :current_user
    before_action :find_spellbook, only: [:show, :edit, :update, :destroy]
    
    def index
        @spellbooks = Spellbook.all 
    end

    def show
        find_spell  
    end

    def recent_spellbooks
        @spellbooks = Spellbook.newest_spellbooks
        render :index
    end

    def new
        @spellbook = Spellbook.new
    end

    def create
        @spellbook = Spellbook.new(spellbook_params)
        if @spellbook.save 
            redirect_to spellbook_path(@spellbook)
        else
            render :new
        end   
    end


    def edit
    end

    def update
        @spellbook.update(spellbook_params)
        if @spellbook.valid?
            redirect_to spellbooks_path
        else
            render :edit
        end
    end

    def destroy
        if current_user.id != @spellbook.user_id
            redirect_to spellbooks_path
        else 
            @spellbook.destroy 
            redirect_to spellbooks_path
        end
    end

    private

    


    def spellbook_params
        params.require(:spellbook).permit(:title, :category, :level)
    end

    def find_spellbook
        @spellbook = Spellbook.find_by_id(params[:id])
    end

    def find_spell
        @spell = Spell.find_by_id(params[:id])
    end

end

app/helpers/spellbooks_helper.rb
module SpellbooksHelper



end

app/views/spellbooks/_form.html.erb
<%= partial_form.label(:title) %>
<%= partial_form.text_field :title %> <br><br>
<%= partial_form.label(:category) %>
<%= partial_form.text_field :category %> <br><br>
<%= partial_form.label(:level) %>
<%= partial_form.number_field :level %> <br><br>
<%= partial_form.hidden_field :user_id, value: current_user.id%>

app/views/spellbooks/edit.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container" style= "text-align:center">
<h1 style="color: #2E1114; text-align:center">Edit Spellbook</h1>

    <% if @spellbook.errors.any? %>
    <div style="list-style-type:none; color: #2E1114; text-align:center" id="error explanation">
        <h2 style="list-style-type:none; color: #2E1114; text-align:center"><%= pluralize(@spellbook.errors.count, "error") %> prevented this Spellbook from being saved: </h2>
        <ul style="list-style-type:none; color: #2E1114; text-align:center">
        <% @spellbook.errors.full_messages.each do |error| %>
        <li> <%= error %></li>
        <% end %>
        </ul>
    </div>
    <% end %>

    <%= form_for @spellbook do |f| %>
        <%= render partial: "form", locals: {partial_form: f }%>
    <%= f.submit "Update your spellbook" %>
    <% end %>
</div>

    <style>
body {
  background: url('https://images.unsplash.com/photo-1497800839469-bdbe4fd9d391?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTB8fG1hZ2ljJTIwaW5ncmVkaWVudHN8ZW58MHx8MHw%3D&auto=format&fit=crop&w=500&q=60') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
}
.container { 
background-color: rgba(100%, 100%, 100%, .3);
border: 2px #83677B;
border-radius: 100px; 
}
</style>

app/views/spellbooks/index.html.erb
<br>
<br>
<br>
<br>
<br>
<div class="container">
<h1 style="color: #2E1114; text-align:center"> All Spellbooks:</h1>
<ul style="list-style-type:none; color: #2E1114; text-align:center">
<% @spellbooks.each do |spellbook| %>
<li> <%= link_to spellbook.title, spellbook_path(spellbook)%> </li>
<% end %>
</ul>

<br><br>
<div style="list-style-type:none; color: #2E1114; text-align:center">
<%= link_to "Click to view the 5 newest spellbooks cast into the portal...", recent_spellbooks_path, class: "btn" %>
</div>
</div>

<style>
body {
  background: url('https://images.unsplash.com/photo-1540650659171-c24a35e9cd54?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NzF8fG1hZ2ljJTIwaW5ncmVkaWVudHN8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
}
.container { 
background-color: rgba(100%, 100%, 100%, .6);
border: 2px #83677B;
border-radius: 100px; 
}

</style>

app/views/spellbooks/new.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
<h1 style="color: #501B1D; text-align:center">Create Spellbook</h1>
    <div style="color: #501B1D; text-align:center">
    <%= render partial: "layouts/error", locals: {object: @spellbook} %>

    <%= form_for @spellbook do |f| %>
        <%= render partial: "form", locals: { partial_form: f } %>
        <%= f.submit "Generate your Spellbook" %>
    <% end %>

    
    </div>
    </div>

    <style>
body {
  background: url('https://images.unsplash.com/photo-1471363159950-bc68f8be7abb?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NXx8d2l0Y2h8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
}
.container { 
background-color: rgba(100%, 100%, 100%, .4);
border: 2px #83677B;
border-radius: 100px; 
}
</style>

app/views/spellbooks/show.html.erb
<br>
<br>
<br>
<br>
<div class="container">
<h1 style="color: #2E1114; text-align:center">Spellbook Information</h1>

<p style="color: #2E1114; text-align:center">
Title: <%= @spellbook.title %>
Category: <%= @spellbook.category %>
Level: <%= @spellbook.level %>
</p>
<div style="color: #501B1D; text-align:center">
<%= link_to "add spell for this spellbook", new_spellbook_spell_path(@spellbook) %>
</div>
 <div style="color: #501B1D; text-align:center">
    
        <!--<%= link_to "edit", edit_spellbook_path(@spellbook) %>
          <%= link_to "delete", spellbook_path(@spellbook), method: 'DELETE' %>-->
  
        </div>

<h5 style="color: #2E1114; text-align:center">All Spells within this Spellbook</h5>



<h6 style="color: #2E1114; text-align:center"><%= render @spellbook.spells %></h6>

</div>

<style>
body {
  background: url('https://images.unsplash.com/photo-1512331455279-c8ae8178f586?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NjV8fG1hZ2ljJTIwaW5ncmVkaWVudHN8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
}
.container { 
background-color: rgba(100%, 100%, 100%, .6);
border: 2px #83677B;
border-radius: 100px; 
}
</style>