config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'

  get 'auth/google_oauth2/callback', to: 'sessions#omniauth'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new' # controller and action
  post '/signup', to: 'users#create'
  resources :users, except: [:destroy]
  
  get '/spellbooks/recent_spellbooks' => 'spellbooks#recent_spellbooks' , as: 'recent_spellbooks'

  resources :crystal_balls
  resources :spells
  resources :spellbooks do
    resources :spells
  end

  match '*path' => 'application_controller#fallback', via: [:all] 

  

 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/spell.rb
class Spell < ApplicationRecord

    belongs_to :spellbook
    belongs_to :user



    validates :name, :description, presence: true
    validates :level, presence: true, numericality: {greater_than: 0, less_than_or_equal_to: 10}


    def self.newest_spells
        Spell.order(created_at: :desc).limit(5)
    end

    def spellbook_attributes=(hash_of_attributes) #custom writer
        if !hash_of_attributes[:title].blank? && !hash_of_attributes[:genre].blank? && !hash_of_attributes[:difficulty].blank?
            self.spellbook = Spellbook.find_or_create_by(hash_of_attributes)
        end
    end

end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
    
    before_action :redirect_if_not_logged_in
    before_action :find_spell, only: [:show, :edit, :update, :destroy]
    before_action :find_spellbook, only: [:show, :edit, :destroy]

    #macro to run particular method before the action methods below execute. Useful because we're able to create validations as well as queries to populate a specific instance variable that we may use within that method. Decreases lines of code and keeps stuff dry. 

    def index
        if params[:spellbook_id] && @spellbook = Spellbook.find(params[:spellbook_id])
            @spells = @spellbook.spells
        else
            @spells = Spell.all
        end
    end

    def show
    end

    def new
        @spellbook = Spellbook.find(params[:spellbook_id])
        @spell = @spellbook.spells.build
        
    end

    def create
        @spell = current_user.spells.build(spell_params)
        @spell.spellbook_id = params[:spellbook_id]
        if @spell.save
            redirect_to spellbook_spell_path(params[:spellbook_id],@spell)
        else
            render :new
        end
    end

    def edit
    end

    def update
        @spell.update(spell_params)
        if @spell.valid? 
            redirect_to spell_path(@spell)
        else
            render :edit
        end
    end

    def destroy
        if authorized_to_edit?
        @spell.destroy
        redirect_to spellbooks_path
        else 
        find_spell 
        end
    end
    
    private
    def spell_params
        params.require(:spell).permit(:name, :level, :description, :spellbook_id, spellbook_attributes: [:id, :user_id, :title, :category, :level])
    end

    def redirect_if_not_spellbook_owner
        find_spell
        find_spellbook
        return redirect_to spells_path unless @spellbook
        redirect_to spells_path unless current_user.id == @spellbook.user_id
    end

    def find_spellbook
        @spellbook = Spellbook.find_by_id(params[:spellbook_id])
    end

    def find_spell
        @spell = Spell.find_by_id(params[:id])
    end
end

app/helpers/spells_helper.rb
module SpellsHelper

    def display_index_header
        if @spellbook 
        content_tag(:h1, "#{@spellbook.title}  Spells")
        else 
        content_tag(:h1, "All Spells")
        end 
   end
    def display_new_header
        if @spellbook 
        content_tag(:h1, "Create a #{@spellbook.title} Spell")
        else 
        content_tag(:h1, "Create a Spell")
        end 
   end
    def book_form_fields(f)
        if @spellbook   # params[:brand_id]
         f.hidden_field :book_id, value: @spellbook.id 
        else 
         render partial: "spellbook_fields", locals: { f: f } 
        end 
    end

end

app/views/spells/_form.html.erb
<%= render partial: "layouts/error", locals: {object: @spell} %>

<%= form_for spell, url:url do |f| %>
    <%= f.label "Name" %>
    <%= f.text_field :name %> <br>
    <%= f.label "Level" %> 
    <%= f.number_field :level %> <br>
    <%= f.label "Description" %> 
    <%= f.text_area :description %> <br>
    <%= f.hidden_field :spellbook_id %>
    <%= f.submit %>
<% end %>

app/views/spells/_spell.html.erb
<p style="color: #501B1D; text-align:center">
<%= link_to(spell.name, spell_path(spell.id) ) %> </p>

<!---<%= link_to(spell.name, spellbook_spell_path(@spellbook, @spell) ) %> </p>-->

app/views/spells/edit.html.erb
<div class="container">
<h1 style="color: #501B1D; text-align:center">Edit Spell</h1>
<div style="color: #501B1D; text-align:center">
<%= render partial: "form", locals: { spell: @spell, url: spell_path(@spell)} %>


</div>
</div>

 <style>
body {
  background: url('https://images.unsplash.com/photo-1554467840-4f2d308f5f25?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MzJ8fHdpdGNofGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
}
.container { 
background-color: rgba(100%, 100%, 100%, .4);
border: 2px #83677B;
border-radius: 100px; 
}
</style>

app/views/spells/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
<h1 style="color: #501B1D; text-align:center">All Spells</h1>

<% @spells.each do |spell| %>
<li style="color: #501B1D; text-align:center"> <%= link_to spell.name, spell_path(spell) %></li>
<% end %>

</div>
<br>
<br>
<br>



  <style>
body {
  background: url('https://images.unsplash.com/photo-1519750783826-e2420f4d687f?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NTl8fG1hZ2ljJTIwaW5ncmVkaWVudHN8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
}

.container { 
background-color: rgba(100%, 100%, 100%, .3);
border: 2px #83677B;
border-radius: 100px; 
}
</style>

app/views/spells/new.html.erb
<br>
<br>
<br>
<br>
<div class="container" style="text-align:center">
<h1 style="color: #501B1D; text-align:center">Create A Spell</h1>
<%= render partial: "form", locals: { spell: @spell, url: spellbook_spells_path(@spellbook)} %>
</div>
   
    <style>
body {
  background: url('https://images.unsplash.com/photo-1497800839469-bdbe4fd9d391?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTB8fG1hZ2ljJTIwaW5ncmVkaWVudHN8ZW58MHx8MHw%3D&auto=format&fit=crop&w=500&q=60') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
}
.container { 
background-color: rgba(100%, 100%, 100%, .3);
border: 2px #83677B;
border-radius: 100px; 
}
</style>

app/views/spells/show.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
<h1 style="color: #501B1D; text-align:center">Spell Info: </h1>

      <div style="color: #501B1D; text-align:center">
      Name: <%= @spell.name %> <br>
      Description: <%= @spell.description %> <br>
      Level: <%= @spell.level %> <br>
      </div>
        <div style="color: #501B1D; text-align:center">
        <% if current_user.id == @spell.user_id %>
        <%= link_to "edit", edit_spell_path(@spell) %>
          <%= link_to "delete", spell_path(@spell), method: 'DELETE' %>
          <% end %>
        </div>
</div>

<style>
body {
  background: url('https://images.unsplash.com/photo-1518562180175-34a163b1a9a6?ixid=MXwxMjA3fDB8MHxzZWFyY2h8OHx8bWFnaWN8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
}
.container { 
background-color: rgba(100%, 100%, 100%, .4);
border: 2px #83677B;
border-radius: 100px; 
}

</style>