config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'

  get 'auth/google_oauth2/callback', to: 'sessions#omniauth'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new' # controller and action
  post '/signup', to: 'users#create'
  resources :users, except: [:destroy]
  
  get '/spellbooks/recent_spellbooks' => 'spellbooks#recent_spellbooks' , as: 'recent_spellbooks'

  resources :crystal_balls
  resources :spells
  resources :spellbooks do
    resources :spells
  end

  match '*path' => 'application_controller#fallback', via: [:all] 

  

 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prevented this from being saved:</h2>

    <ul style="list-style-type:none;">
        <% object.errors.full_messages.each do |error| %>
        <li><%= error %></li>
        <% end %>
    </ul>
    </div>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wizzards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </head>
<body class="l-box" style="background-color: #83677B;">
<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #2E1114;">
  <div class="container-fluid">
    <a class="navbar-brand fw-bold" style="color: #ADADAD;" href="/">Hocus Pocus Portal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="nav justify-content-end">
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <% if !logged_in? %>
          <li><%= link_to "Log in with Google", '/auth/google_oauth2', method: :post, class:"nav-link"%></li>
          <li><%= link_to 'Sign-Up', "/signup", class:"nav-link"%></li>
          <li><%= link_to 'Log in', "/login", class:"nav-link"%></li>
          <% else %>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" style="color: #ADADAD;" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Users
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><%= link_to 'All Users', users_path, class: "dropdown-item"%></li>
            <li><%= link_to 'Update User', edit_user_path(current_user), class: "dropdown-item"%></li>
          </ul>
          </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" style="color: #ADADAD;" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Spellbooks
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><%= link_to 'All Spellbooks', spellbooks_path, class: "dropdown-item"%></li>
            <li><%= link_to 'Create a Spellbook', new_spellbook_path, class: "dropdown-item"%></li>
          </ul>
          </li>
          <li class="nav-item dropdown">
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          </ul>
          </li>
                <li class="nav-item">
          <%= link_to "Logout", logout_path, method: 'delete', class:"nav-link", style:"color: #ADADAD;" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <div><%= flash[:message] %></div>
    <%= yield %>
</body>

</html>